export const MEETING_EXTRACTION_TARGET_WINDOW_MS = 180_000;
export const MEETING_EXTRACTION_OVERLAP_WINDOW_MS = 30_000;
export const MEETING_EXTRACTION_MAX_RETRIES = 3;
export const MEETING_EXTRACTION_RETRY_BASE_DELAY_MS = 1_000;
