export const STREAM_SESSION_STORE = Symbol("STREAM_SESSION_STORE");

export const DEFAULT_AUDIO_BUFFER_FLUSH_MS = 10_000;
export const DEFAULT_AUDIO_BUFFER_MAX_CHUNKS = 5;
export const DEFAULT_AUDIO_BUFFER_IDLE_TIMEOUT_MS = 30_000;
